CreateEventInput:
    type: input-object
    config:
        fields:
            key:
                type: String!
            name:
                type: String!
            date:
                type: DateTime!
            participants:
                type: "[String!]!"
            program:
                type: "[SpeechInput!]!"
SpeechInput:
  type: input-object
  config:
    fields:
      topic:
        type: "String!"
      speaker:
        type: "String!"
      startTime:
        type: "Int!"
      endTime:
        type: "Int!"