NodeInterface:
    type: interface
    config:
        resolveType: '@=resolver("App\\GraphQL\\Resolver\\NodeInterfaceResolver::resolveType", [value, typeResolver])'
        fields:
            id:
                type: ID!
